[project]
name = "uv-spec"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.9.2",
    "pandas>=2.2.3",
    "pyqt6>=6.7.1",
    "ruff>=0.7.2",
    "scipy>=1.14.1",
]
